### ISSUE TITLE
Support of systemd restart=always option for keepalived

### ISSUE THREAD

**Issue by al-ti** [evrardjp/ansible-keepalived#131]
Hello, for my setup I would prefer to have Restart = always in /etc/systemd/system/keepalived.service.d/override.conf

Use case: 
In my setup I have keepalived mapped to network interface which doesn't exist on boot time, and get's added in few minutes after. Meanwhile keepalived crashes with error:
#
VRRP is trying to assign ip address   to unknown   interface !!! go out and fix your conf !!!
#

And without restart=always option keepalived won't start automatically after adding interface. 
I'm not sure if it can be interesting for community or no, or maybe it was not added on purpose. 
How do you think adding such optional parameter can be on handy? If so, I can prepare PR for this. We might thing on a customizable list of settings for systemd unit. If there are reasons not to do this - it's fine.

**Comment by evrardjp** [comment]
I think if it's an optional behaviour, it's an okay addition. You would need to make this conditional by introducing a default value in `defaults/main.yml`, a boolean check ` | bool` in the tasks and/or templates, and a change in the documentation. But it's a welcomed PR.

**Comment by al-ti** [comment]
Thank you for replay, I'll work on it.

**Comment by elcomtik** [comment]
I was thinking about enhancement of the role by adding a possibility to add custom overrides. In my use case, keepalived is doing vrrp communication over tunnel interface, which is managed by wireguard daemon. Tunel interface needs to be up before keepalived, so another dependency needs to be added. This feature would need to be done in a manner to not interfere with overrides already used.

However, after reading this issue, I think using restart=always is much easier to implement and the final outcome will be the same.

I can make PR for this issue

**Comment by evrardjp** [comment]
Thanks a lot! That is indeed welcomed. I would prefer if restart=always as an option, to not change the current behaviour by default. If you want to go into more work to add a custom override, I wouldn't be against it either. I just believe these are two different topics :)

**Comment by elcomtik** [comment]
I agree with you, custom overrides is another topic. I originally wanted to create such an issue, however when I discovered another solution to the same problem I converged to simply it and solve this one.

I will make this allway=restart override optional.

**Comment by elcomtik** [comment]
It is ready to review

**Comment by elcomtik** [comment]
this issue may be closed
