### ISSUE TITLE
The role and its CI need modernization

### ISSUE THREAD

**Issue by evrardjp** [evrardjp/ansible-keepalived#160]
First, an introduction of the role.

Currently the role is supporting systemd/upstart on centos7+, debian, SUSE, ubuntu 14.04+
The semaphore CI is based on ubuntu 14.04. The Vagrant testing (manual testing) is multi distro, and is testing they all work together/behave fine. Both are needed for complete coverage.

Here are a few recent problems:

- Vagrant is annoying, as I have different configuration in different machines, and it's just a pain depending on the backend. I would prefer moving to containers and molecule.
- In my Vagrant machines on my latest local environments, I am hitting issue https://github.com/ansible/ansible/pull/72337
- When I replaced Vagrant with molecule (to ease the developer workflow as mentioned above), I also hit the same problems.
- My CI on 14.04 doesn't have the same problems.
- The role is outdated, has a lot of ansible workarounds that shouldn't exist anymore (no need to install python-apt packages anymore, it's done automatically nowadays!)
- The role can be simplified.

So what I want to do:
- To be able to test changes in this role, I need to introduce the workaround for more recent distros, so I can still have coverage.
- Release one last version compatible with 14.04.
- Remove 14.04 support. With this, I can remove non-systemd support.
- Introduce molecule testing, this should still work because the workaround is still in place
- Cleanup the role, while keeping this role workarounds.
- Wait for the upstream workaround to be merged on ansible 2.9+, wait for ansible 2.8 to be un-supported, then revert workarounds to be clean "service" modules.

WDYT?

**Comment by noonedeadpunk** [comment]
I'm not sure that this workaround is needed for 14.04. Out of current PRs I don't really see improvements for 14.04 but it's more about general role improvements as well as CI.
So probably worth to tag 14.04 now and proceed with the rest of the list?

**Comment by evrardjp** [comment]
The workaround is _not_ needed for 14.04, but any change going on will not pass _complete_ testing without the workaround.

**Comment by evrardjp** [comment]
I think I am fine with accepting the current state, tag, and move on, if that's what you mean.

**Comment by evrardjp** [comment]
As @noonedeadpunk represents one of this role's biggest users, I am fine with moving on. Thanks for your opinion @noonedeadpunk !

**Comment by noonedeadpunk** [comment]
> I think I am fine with accepting the current state, tag, and move on, even if the last release is broken. If that's what you mean.

Yeah, it's exactly what I meant. At least it's not broken for 14.04 and for the rest there are most of the PRs present so will be able to extend CI and test everything properly (and make new tag) pretty fast I think.

**Comment by evrardjp** [comment]
> > I think I am fine with accepting the current state, tag, and move on, even if the last release is broken. If that's what you mean.
> 
> Yeah, it's exactly what I meant. At least it's not broken for 14.04 and for the rest there are most of the PRs present so will be able to extend CI and test everything properly (and make new tag) pretty fast I think.
> 
> > will not pass _complete_ testing without the workaround
> 
> Most likely that CI has very modern kernel, that is not shipped with any of the supported OS out of the box, so in real deployments things should not be broken

Currently the CI is running 14.04, and I can swap it into 18.04 which doesn't have the problem. The problem just appears on docker container running 20.04 or others.

**Comment by evrardjp** [comment]
Modernization is happening on the 'cleanup' branch and PR.
