### ISSUE TITLE
SE Linux blocking loading of scripts as non root user 

### ISSUE THREAD

**Issue by spookiej** [evrardjp/ansible-keepalived#165]
**Problem**
I am looking to run scripts as non-root user so that auditd does not log every healthcheck run by the root user. SE Linux blocks this so am wondering how to add this to the role.

I do have a solution, but it is not implemented the same way that you have implemented this in the role.

I had a look at the way that the selinux policy modules are built and compiled, but I wasn't able to make much progress.

Any advice for implementing the below capability in the policy module files, or interest in the below being working this into the role?

**Solution**
```
cat > local_keepalived.cil << EOF
(allow keepalived_t keepalived_t (capability (setuid setgid)))
EOF
semodule -i local_keepalived.cil
```

**Edit**
looks like with audit2allow I was able to generate the te file. Are you interested in me doing a PR for this? 
```
module keepalived_t 1.0;

require {
        type keepalived_t;
        class capability { setgid setuid };
}

#============= keepalived_t ==============
allow keepalived_t self:capability { setgid setuid };
```

**Comment by evrardjp** [comment]
@spookiej sure! I would love to see a PR! :)

**Comment by evrardjp** [comment]
Should I close this?
