### ISSUE TITLE
issue in testing with debian 11 aka bullseye

### ISSUE THREAD

**Issue by zerwes** [evrardjp/ansible-keepalived#192]
@zerwes If there is an issue in testing with debian11, would you mind filing an issue for it, with the logs? We'll try to figure it out. It's probably a molecule thing again.

_Originally posted by @evrardjp in https://github.com/evrardjp/ansible-keepalived/issues/189#issuecomment-1017260054_

**Comment by zerwes** [comment]
while running `molecule test` on debian 11 with
```
$ molecule --version
molecule 3.5.2 using python 3.9 
    ansible:2.12.1
    delegated:3.5.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```
I get in the converge step
`INFO     Running default > converge`
a error related to systemd not beeing available in the docker image
```
TASK [ansible-keepalived : Check if keepalived is enabled] *********************
fatal: [keepalived-bionic]: FAILED! => {"changed": false, "cmd": "systemctl daemon-reload && systemctl is-enabled keepalived.service", "delta": "0:00:00.004321", "end": "2022-01-20 19:34:58.212965", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2022-01-20 19:34:58.208644", "stderr": "Failed to connect to bus: No such file or directory", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
```
(seems to fail on every image i.e.:
```
TASK [ansible-keepalived : Check if keepalived is enabled] *********************
fatal: [keepalived-centos7]: FAILED! => {"changed": false, "cmd": "systemctl daemon-reload && systemctl is-enabled keepalived", "delta": "0:00:00.469191", "end": "2022-01-20 20:55:46.937047", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2022-01-20 20:55:46.467856", "stderr": "Failed to get D-Bus connection: No such file or directory", "stderr_lines": ["Failed to get D-Bus connection: No such file or directory"], "stdout": "", "stdout_lines": []}
```
I thing this is related to the geerlingguy images ... (I can recall that in another context I had some issues with them too), but docker and molecule are not my area of expertise, so this might be only half of the truth ...

On the branch [fix-docker](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-keepalived/tree/fix-docker) I have created a working molecule scenario with a self build docker image with debian 11 and systemd working on debian 11 ...

I try to find out some more details if I find the time ...

**Comment by evrardjp** [comment]
Thanks for the first pass, and first documentation!
I am not running debian myself, so it makes it a bit harder. 

I however will highlight that you're looking for help.

**Comment by evrardjp** [comment]
I will try to find time to compare, and maybe fix a few things.

For the images, it's been a back and forth between different images in the past.
I think it would make sense to fix the upstream images rather than carrying our own.

**Comment by zerwes** [comment]
> I think it would make sense to fix the upstream images rather than carrying our own.

I fully agree to this, the commit was just a example. As I mentioned, is stumbled over the problems with the  geerlingguy images before, but did not find the time to dive deeper into it.
As those images are quite popular, maybe the error is in my docker setup (as I mentioned, I am rather a simple user on that topic)
If I can provide some more information, just let me know.

**Comment by zerwes** [comment]
opened geerlingguy/docker-debian11-ansible#4

**Comment by evrardjp** [comment]
TBH, I had issues also in the past with those images. I brought my own images, but it was a burden to maintain.

**Comment by zerwes** [comment]
I fully agree ... for a q&d test some self build images are totally OK. With the full implication the burden you mentioned ...
But as the geerlingguy images are really widely used, I think the intention to fix them upstream (or at least to understand why they fail here) is more in the interest of the open source idea then everybody brewing it's own beer.
So if you have any idea, what I can test with a reasonable effort and expense of resources just let me know.

**Comment by evrardjp** [comment]
I fully agree with you. 

If I have an idea, I will let you know. Let's sync over the other thread. In the meantime, you can use github actions to test your patches.
