### ISSUE TITLE
Linting fails since ansible lint is updated

### ISSUE THREAD

**Issue by evrardjp** [evrardjp/ansible-keepalived#197]
We now have the problem that we can't use the "short" name for tasks.

See also the lint failures: `fqcn-builtins Use FQCN for builtin actions.`

**Comment by evrardjp** [comment]
See also:

- https://github.com/ansible/ansible-lint/pull/1614
- https://github.com/ansible/ansible-lint/pull/1908
- https://github.com/ansible/ansible-lint/issues/2050

**Comment by zerwes** [comment]
yes, I like those breaking changes in ansible too :-/

but with the simple fix from the PR +199
```diff
+ All checks have passed
+ 3 successful checks
```
