### ISSUE TITLE
Solution to a mis-configuration of the task "Dropping the tracking scripts" that should save you hours of debugging

### ISSUE THREAD

**Issue by Infouzi** [evrardjp/ansible-keepalived#233]
Hi, this is not really an issue, but a solution to a problem i faced yesterday (all day), when trying to use the "master" example in the **test directory**.

When you want to use the "src_xxx_script" and add them, it will not work, because the "main.yml" in the task folder has a small mis-configuration into it, i assume due to a copy/paste probably. 

When debugging, you will find that the "items" of the block "**keepalived_scripts**" are not detected while doing the "Dropping the tracking scripts" task. 

Solution: You should modify the "loop" parameter and have "keepalived_scripts" instead of "keepalived_sync_groups", 

### Before: 
`
- name: Dropping the tracking scripts
........
  loop: "{{ **keepalived_sync_groups** | dict2items | default('{}') }}"
.......
`

### After

`
- name: Dropping the tracking scripts
........
  loop: "{{ **keepalived_scripts** | dict2items | default('{}') }}"
.......
`

That's it, i hope it helps many, or the author to modify the script. Thank you.

**Comment by evrardjp** [comment]
Thanks @Infouzi ! I will check this! It seems indeed the docs could deserve some love.

**Comment by evrardjp** [comment]
I cleaned up the examples now.

**Comment by Infouzi** [comment]
> I cleaned up the examples now.

Perfect, and good luck for the rest. <3
