### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rxbn** [evrardjp/ansible-keepalived#272]
Hi!

First of all, thank you so much for creating this Ansible role!

Could you please create a new release, so that the bug regarding Ansible check mode is fixed: https://github.com/evrardjp/ansible-keepalived/pull/232

Thank you!

Many thanks,
-- Robin

**Comment by evrardjp** [comment]
Hello,

Yes, it seems it's an omission of my part, sorry for that!

Allow me to merge a few things, and release again.

**Comment by rxbn** [comment]
Sure, thanks!

**Comment by evrardjp** [comment]
Done. 

I am still without a linux laptop, so sometimes the whole contributions are slow. 

Sorry for the inconvenience.

**Comment by rxbn** [comment]
Thank you very much :)
