### ISSUE TITLE
Support of nopreempt parameter

### ISSUE THREAD

**Issue by berendt** [evrardjp/ansible-keepalived#4]
At the moment it is not possible to set the ``nopreempt`` parameter for an instance. I think it makes sense to support it.

**Comment by evrardjp** [comment]
Hello, 

Sorry for the long wait. This makes perfectly sense.
I'll hack something later today.

**Comment by evrardjp** [comment]
Hello, 

nopreempt support is now merged into master branch.
Tag will be updated next Monday.
