### ISSUE TITLE
Old version on Ansible Galaxy

### ISSUE THREAD

**Issue by justinsaliba** [evrardjp/ansible-keepalived#50]
Hi,

Is there a reason why the latest versions of this role aren't available in Ansible Galaxy? I noticed that versions stopped at v2.6.2.

The option I'm taking right now is to clone this repository via Git to the roles/ folder in my playbook folder and checkout to the latest tag (3.0.3). I was wondering whether there's a better option available?

Thanks :)

**Comment by justinsaliba** [comment]
@evrardjp would it be possible to upload the latest version on Ansible Galaxy please?

**Comment by evrardjp** [comment]
Hello.

Sorry I missed the first notification on the issue.
Yes, I will upload the latest version in galaxy.

Sorry for the inconvenience. 

Best regards,
JP

**Comment by evrardjp** [comment]
Updated.

If you have additional questions/require an update, please tell us!

Best regards.

**Comment by justinsaliba** [comment]
thanks :) ... sorry I just saw this message.

**Comment by evrardjp** [comment]
No worries!
