### ISSUE TITLE
keepalived_instances default?

### ISSUE THREAD

**Issue by rlex** [evrardjp/ansible-keepalived#58]
Hello, any particular reason why keepalived_instances set as [] instead of {} by default? That causes issues when you run "empty" role on hosts where keepalived not supposed to run (ie if you run playbooks conditionally).

Also, why debian vars file was removed?

**Comment by evrardjp** [comment]
Good question, sorry for the late answer. Will investigate right now!

**Comment by evrardjp** [comment]
Good catch on those! I have to blame myself on the keepalived_instances: []
Probably rest of something before the first upstreaming!

**Comment by evrardjp** [comment]
For debian support, I am not sure it was "removed" but never there in the first place. Or I might be wrong. I can fix that for you, but I am not testing it right now. I will change my testing to include it then, but it could take a while.

**Comment by evrardjp** [comment]
The [] is fixed in master. Will tag a release soon, with a few other fixes included. For debian support I will test how hard would it be before claiming to support it.

**Comment by rlex** [comment]
Debian vars just in case:
```
keepalived_package_name: "keepalived"
keepalived_service_name: "keepalived"
keepalived_config_file_path: "/etc/keepalived/keepalived.conf"
```

**Comment by evrardjp** [comment]
Thanks :) I was just having the same content, so I am glad we are sharing here! 

I moved to use native package install instead of ppa using debian.

**Comment by evrardjp** [comment]
We should probably separate this issue in two though.

**Comment by rlex** [comment]
About ifconfig - it's generally considered deprecated (but still available as external package at least in deb9)
ip is considered modern replacement, so probably it's better to switch to it. 
AFAIK centos 7 also dropped ifconfig from base install.

**Comment by evrardjp** [comment]
Yes I am aware of this, I am generally using ip link for replacement. I am using both to make sure everything is ok in all cases.

Debian support has merged now. https://github.com/evrardjp/ansible-keepalived/commit/94cb617fc06460df07fa8ae293c9d020112a2e76

**Comment by rlex** [comment]
Thank you for your work!
