### ISSUE TITLE
need uninstallation config

### ISSUE THREAD

**Issue by vanloswang** [evrardjp/ansible-keepalived#67]
There is no uninstallation yaml configuration file provided by ansible-keepalived?

**Comment by evrardjp** [comment]
There is none indeed. You're the first one to ask that :)

Patches are welcome to provide an example playbook for removal.

I'd say most of the changes can be done by removing the packages, the eventual package sources, and removing the configuration/daemon files (should you not want to keep a backup).

For the first part (removing the packages), you can run the role with set: keepalived_package_state to absent. I haven't tested it, but it should do the trick.
For the configuration files, you will need to remove files in /etc/keepalived. I guess there is a question whether this should be automatic or not when removing packages, but that's something I leave to you :)
For the sources/daemon file, it depends on previous variable settings. We can I guess remove the files if those variables are set?

Thank you in advance.

**Comment by evrardjp** [comment]
I suppose this was enough for your use case. Thank for your issue!
